builds:
  - binary: php-fpm_exporter
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
      - 386

changelog:
  filters:
    exclude:
      - '^docs:'

archives:
  - id: default
    format: binary
  - id: targz
    format: tar.gz
